name: Build
on: [push, pull_request, workflow_call]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Typecheck
        run: npm run types

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test:unit

      - name: Prepare for Integration Tests
        run: npm run demo:build

      - name: Integration Tests
        run: npm run test:integrationOnly
