name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Typecheck
        run: yarn types
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Unit Tests
        run: yarn test:unit
      - name: Prepare for Integration Tests
        run: yarn demo:build
      - name: Integration Tests
        run: yarn test:integrationOnly
